///|
pub let api_accounts : String = "/api/accounts"

///|
pub fn api_account(id : Int) -> String {
  "/api/accounts/\{id}"
}

///|
pub let api_categories : String = "/api/categories"

///|
pub let api_transactions : String = "/api/transactions"

///|
pub fn api_transaction(id : Int) -> String {
  "/api/transactions/\{id}"
}

///|
pub let api_budgets : String = "/api/budgets"

///|
pub fn api_budget(id : Int) -> String {
  "/api/budgets/\{id}"
}

///|
pub let api_dashboard : String = "/api/dashboard"
