name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install moonup
        uses: chawyehsu/setup-moonup@v1

      - name: Install nightly toolchain
        run: |
          moonup install nightly
          moonup default nightly

      - run: moon version --all

      - name: Install dependencies
        run: moon update && moon install

      - name: Check
        run: moon check

      - name: Build JS
        run: moon build --target js

      - name: Build Native
        run: moon build --target native

      - name: Test
        run: moon test
